# Publish the documentation on merge and nightly
name: Publish the book

on:
  push:
    branches: [main]
  schedule:
    # every day at 4:00 -- ready for my morning coffee
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Build with Sphinx
        run: |
          pip install -r requirements.txt
          sphinx-build -b html book book/_build/html

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/_build/html
          clean: true
