name: Test the book

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2.3.1

      - name: Jupyter Book cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ./jupyter_cache
          key: ${{ github.event.number }}-jupyter-cache-${{ github.run_id }}
          restore-keys: |
            ${{ github.event.number }}-jupyter-cache

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build the book
        run: |
          mkdir -p ./jupyter_cache
          ls ./jupyter_cache
          jupyter-book build -n --keep-going book
          ls ./jupyter_cache
