name: Test the book

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2.3.1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build the book
        run: |
          jupyter-book build -nW --keep-going book
